#ifndef GLOBAL_STRUCTS_H
#define GLOBAL_STRUCTS_H

typedef enum {
    DEV_STATE_NONE,
    DEV_STATE_VOLTMETER,
    DEV_STATE_OHMMETER,
    DEV_STATE_FREQUENCY_READ,
    DEV_STATE_PULSE_GEN,
    DEV_STATE_ADV_SPI_TEST_DISPLAY,
} dev_state_t;

#endif
