#ifndef GLOBAL_STRUCTS_H
#define GLOBAL_STRUCTS_H

typedef enum {
    DEV_STATE_NONE,
    DEV_STATE_VOLTMETER,
    DEV_STATE_OHMMETER,
    DEV_STATE_FREQUENCY_READ,
    DEV_STATE_DETECT_PULSE_UP,
    DEV_STATE_DETECT_PULSE_DOWN,
    DEV_STATE_PULSE_GEN,
} dev_state_t;

#endif
